# Generated by Django 4.2.3 on 2023-07-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('usertype', models.CharField(choices=[('ADMIN', 'INSTRUCTOR'), ('USER', 'NORMAL')], default='USER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user_logged', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
            options={
                'db_table': 'login_logs',
            },
        ),
    ]
